name: odak_balkonu
description: "Odağını büyüt, balkonunu yeşert."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path: ^1.9.1
  path_provider: ^2.1.6
  sqlite3_flutter_libs: ^0.6.0+eol

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  drift_dev: ^2.34.5

flutter:
  uses-material-design: true
